# Site settings
title: Carmina
email: lojacarmina@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Loja Carmina - Tudo o que precisa em vila nova de Famalicão...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carmina.pt" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: utf-8
