- name: Pilhas
  description: Colocação de pilhas
  url: 01.jpg

- name: Brinquedos
  description: Brinquedos para todos os gostos
  url: 02.jpg

- name: Pequena Eletrónica
  description: Calculadoras, despertadores...
  url: 03.jpg

- name:  Brinquedos de Coleção
  description: Brinquedos para todos os gostos
  url: 04.jpg
