- name: Canivetes suíços
  description: Varias marcas...
  url: 01.jpg

- name: Pilhas
  description: Colocação de pilhas, braceletes e arranjo de relógios.
  url: 02.jpg

- name: Miniaturas de coleção
  description: Coleçoes completas
  url: 03.jpg

- name:  Brinquedos
  description: Brinquedos para todos os gostos
  url: 04.jpg
